# Generated by Django 3.2.7 on 2021-10-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='created_by',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
